# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#publishing build artifacts
- task: CopyFiles@2
  displayName: 'Copy File to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*.sh 
      **/*.war
      **/*jar-with-dependencies.jar
    TargetFolder: '$(System.DefaultWorkingDirectory)/pipeline-artifacts/'
    flattenFolders: true 

- task: AzureImageBuilderTask@1
  displayName: 'Azure VM Image Builder Task'
  inputs:
    managedIdentity: '/subscriptions/811c6604-f6fb-46f9-a016-66bd96c6a0cd/resourcegroups/myVMSSResourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myVMSSIdentity'
    imageSource: 'marketplace'
    packagePath: '$(System.DefaultWorkingDirectory)/pipeline-artifacts'
    inlineScript: |
      sudo mkdir /lib/buildArtifacts
      sudo cp  "/tmp/pipeline-artifacts.tar.gz" /lib/buildArtifacts/.
      cd /lib/buildArtifacts/.
      sudo tar -zxvf pipeline-artifacts.tar.gz
      sudo sh install.sh
    storageAccountName: 'scalesetnew'
    distributeType: 'sig'
    galleryImageId: '/subscriptions/811c6604-f6fb-46f9-a016-66bd96c6a0cd/resourceGroups/myVMSSResourceGroup/providers/Microsoft.Compute/galleries/myVMSSGallery/images/MyImage'
    replicationRegions: 'eastus2'
    ibSubscription: '4510c13a-fe42-4147-90b2-a3f5d46c8be3'
    ibAzureResourceGroup: 'myVMSSResourceGroup'
    ibLocation: 'eastus2'